apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: ingress
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.domainname }}
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: {{ .Values.port }}