apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    srvc: {{ .Release.Name }}-service

spec:
  selector:
    app: {{ .Release.Name }}-back
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    protocol: "TCP"